spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            kudu:  #kudu数据源
                enabled: false      #是否开启
                isKerberos: false   #是否为Kerberos认证模式
                driverClassName: com.cloudera.impala.jdbc41.Driver
#                url: jdbc:impala://192.168.1.46:21050/kudu_test
                url: jdbc:impala://{0}:21050/;AuthMech=1;KrbRealm={1};KrbHostFQDN={0};KrbServiceName=impala
                username:
                password:
            first:  #数据源1 oracle
                driverClassName: oracle.jdbc.driver.OracleDriver  # oracle驱动
                url: jdbc:oracle:thin:@10.226.95.174:1521:SCPDCP
                username: PIWEB
                password: init1234
            second:  #数据源2 db2
                driverClassName: com.ibm.db2.jcc.DB2Driver   # db2驱动
                url: jdbc:db2://10.228.201.188:50000/fh79dwab
                username: db2admin
                password: db2admin
#            three:  #数据源3 mysql
#                driverClassName: com.mysql.jdbc.Driver    # mysql驱动
#                url: jdbc:mysql://localhost:3306/fvw?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#                username: root
#                password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
#                login-username: admin
#                login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 127.0.0.1
        port: 6379
        password:    # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接
http:
  #最大连接数
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
  #证书路径
  keyStorePath: /usr/https_cert/keystore.jks
  #证书密码
  keyStorepass: 123456

abf:
    log:
       logFile : D:\piWebSchedule\onlineDataLocalLog.txt
       localSupplementLog : D:\piWebSchedule\localSupplementLog.txt
       firstReadLog : D:\piWebSchedule\onlineDataShareLog.txt
       pdfLogFile : D:\piWebSchedule\pdfDataLocalLog.txt
       firstPdfLog : D:\piWebSchedule\pdfDataShareLog.txt
       firstStart : D:\piWebSchedule\firstStart
       beginTime : 2020-08-13 23:59:59
       path: D:\piWebSchedule\logs
onlinedata:
    dirobj :
        targetmap : {
          txt : 'd:\piWebSchedule\onlineData\txt',
          demoB8L : 'd:\piWebSchedule\onlineData\demo\B8L',
          demoCCFB : 'd:\piWebSchedule\onlineData\demo\CCFB',
          demoCCSB : 'd:\piWebSchedule\onlineData\demo\CCSB',
          superAlmost : 'd:\piWebSchedule\onlineData\pdf\superAlmost',
          stablePassRate : 'd:\piWebSchedule\onlineData\pdf\stablePassRate',
        }
        sharemaplist:
            txt:
              - '\\\\10.228.165.206\onlinedata'
              - '\\\\10.228.165.209\onlinedata'
              - '\\\\10.228.165.211\onlinedata'
            demoB8L:
              - '\\\\10.228.165.173\Export\B8L'
              - '\\\\10.228.165.178\Export\B8L'
            demoCCFB:
              - '\\\\10.228.165.173\Export\CCFB'
              - '\\\\10.228.165.178\Export\CCFB'
            demoCCSB:
              - '\\\\10.228.165.173\Export\CCSB'
              - '\\\\10.228.165.178\Export\CCSB'
            superAlmost:
              - '\\\\faw-vw.in\fs\org\P-Q-MT\p-q-mt\SQL-DATA\list\AU581'
              - '\\\\faw-vw.in\fs\org\P-Q-MT\p-q-mt\SQL-DATA\list\B8L'
            stablePassRate:
              - '\\\\faw-vw.in\fs\org\P-Q-MT\p-q-mt\SQL-DATA\sta\AU581'
              - '\\\\faw-vw.in\fs\org\P-Q-MT\p-q-mt\SQL-DATA\sta\B8L'
pdfextract:
    confobj :
       superAlmost: {
         factory : 1,
         carName : 2,
         categoryData : 3,
         partName : 4,
         measurePoint : 5,
         oTol : 6,
         uTol : 7,
         deviation : 8,
         createTime : 9
       }
       stablePassRate : {
          factory : 0,
          carName : 1,
          categoryData : 2,
          partName : 3,
          stableFuncGreen : 4,
          stableFuncYellow : 5,
          stableFuncRed : 6,
          stableComGreen : 7,
          stableComYellow : 8,
          stableComRed : 9,
          passrateFuncGreen : 10,
          passrateFuncYellow : 11,
          passrateFuncRed : 12,
          passrateComGreen : 13,
          passrateComYellow : 14,
          passrateComRed : 15,
          createTime : 16
       }